services:

  primary:
    image: postgres:18
    container_name: primary
    restart: unless-stopped
    environment:
      - POSTGRES_DB=my_app_db
      - POSTGRES_USER=aglaya
      - POSTGRES_PASSWORD=aglaya_password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/primary:/var/lib/postgresql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=5
      -c wal_keep_size=1024MB
      -c shared_buffers=256MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aglaya -d my_app_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  replica:
    image: postgres:18
    container_name: replica
    restart: unless-stopped
    depends_on:
      primary:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/tmp/entrypoint.sh"]
    environment:
      - PGDATA=/var/lib/postgresql/18/docker
    ports:
      - "5433:5432"
    volumes:
      - ./db_data/replica:/var/lib/postgresql
      - ./db_init/entrypoint.sh:/tmp/entrypoint.sh:ro

  my-app:
    build: .
    container_name: my-app
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      primary:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://primary:5432/my_app_db
      - SPRING_DATASOURCE_USERNAME=aglaya
      - SPRING_DATASOURCE_PASSWORD=aglaya_password

  # Вторая копия приложения
  my-app-2:
    build: .
    container_name: my-app-2
    restart: unless-stopped
    ports:
      - "8086:8085"  # ← Внешний порт 8086, внутренний 8085
    depends_on:
      primary:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://primary:5432/my_app_db
      - SPRING_DATASOURCE_USERNAME=aglaya
      - SPRING_DATASOURCE_PASSWORD=aglaya_password
      - APP_INSTANCE_NAME=my-app-2  # ← Другое имя экземпляра

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-app
      - my-app-2

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube_local
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/extensions:/opt/sonarqube/extensions
      - ./sonar/logs:/opt/sonarqube/logs

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin