# Количество рабочих процессов (auto = по количеству CPU ядер)
worker_processes auto;

events {
    # Максимальное количество одновременных соединений на один рабочий процесс
    worker_connections 1024;
}

http {
    # Формат логов для отладки
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent"'
                    'upstream: $upstream_addr';

    access_log /var/log/nginx/access.log main;

    # Upstream — группа бэкендов, между которыми будем балансировать
    # Пока у нас только один, но скоро добавим второй
    upstream my_app_backend {
        server my-app:8085;  # Имя сервиса из docker-compose + порт
        server my-app-2:8085;
    }

    # Виртуальный сервер (слушает на порту 80)
    server {
        listen 80;

        # Все запросы перенаправляем на upstream
        location / {
            proxy_pass http://my_app_backend;

            # Передаем оригинальные заголовки в бэкенд
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}