CREATE TABLE IF NOT EXISTS email_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient   VARCHAR(200) NOT NULL,
    subject     VARCHAR(200) NOT NULL,
    text        TEXT NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attempts    INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at     TIMESTAMP NULL
);

CREATE INDEX idx_email_outbox_status ON email_outbox(status);